### PR TITLE
fix inaccuracy in JanusBoard::moveFromSanString

### LINKED ISSUE #316: Failing test in debug mode
When running in debug mode (tested under Linux, gcc and clang), I see a failing Q_ASSERT.

```
QFATAL : tst_Board::moveStrings(janus castling san1) ASSERT: "!move.isNull()" in file src/board/board.cpp, line 665
FAIL!  : tst_Board::moveStrings(janus castling san1) Received a fatal error.
```
The line in question is:
```
Q_ASSERT(!move.isNull());
```
I was unable to figure out why move is null.

### PR DESCRIPTION
**Pull request by alwey**
resolves #316

### CODE REVIEW

File: projects/lib/src/board/janusboard.cpp [hunk 1]
```diff
@@ -92,13 +92,13 @@ Move JanusBoard::moveFromSanString(const QString& str)
 	if (hasCastlingRight(sideToMove(), KingSide))
 	{
 		Move castlingMove = WesternBoard::moveFromSanString("O-O");
-		if (str == sanMoveString(castlingMove))
+		if (castlingMove != Move() && str == sanMoveString(castlingMove))
```
Comment (ilaripih) [inline projects/lib/src/board/janusboard.cpp]: I think that instead of `castlingMove != Move()` you could write `!castlingMove.isNull()`

Comment (alwey) [reply projects/lib/src/board/janusboard.cpp]: Thank, you. This is much better. Changed accordingly.
